/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertergps;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author felipeneves
 */
public class NewJFrame extends javax.swing.JFrame {

    ArrayList<String> diretorios;
    String diretorio;
    ConverterGPS converter;
    Zip zip;

    public NewJFrame() {
        converter = new ConverterGPS();
        zip = new Zip();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_areaDiretorio = new javax.swing.JPanel();
        txtFild_recDiretorio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton_abrirArquivo = new javax.swing.JButton();
        jButton_abrirPasta = new javax.swing.JButton();
        jRadioButton_GPS = new javax.swing.JRadioButton();
        jRadioButton_BIL = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_areaEventos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_linhasConvertidas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton_converterVarios = new javax.swing.JButton();
        jButton_converterArquivo = new javax.swing.JButton();
        jButton_Zip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_areaDiretorio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diretorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malayalam MN", 2, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jButton_abrirArquivo.setText("Abrir Arquivo");
        jButton_abrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrirArquivoActionPerformed(evt);
            }
        });

        jButton_abrirPasta.setText("Abrir Pasta");
        jButton_abrirPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abrirPastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_abrirArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_abrirPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_abrirPasta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButton_abrirArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jRadioButton_GPS.setText("GPS");
        jRadioButton_GPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_GPSMouseClicked(evt);
            }
        });
        jRadioButton_GPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_GPSActionPerformed(evt);
            }
        });

        jRadioButton_BIL.setText("BIL");
        jRadioButton_BIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton_BILMouseClicked(evt);
            }
        });
        jRadioButton_BIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_BILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_areaDiretorioLayout = new javax.swing.GroupLayout(jPanel_areaDiretorio);
        jPanel_areaDiretorio.setLayout(jPanel_areaDiretorioLayout);
        jPanel_areaDiretorioLayout.setHorizontalGroup(
            jPanel_areaDiretorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_areaDiretorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFild_recDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel_areaDiretorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_GPS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_BIL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_areaDiretorioLayout.setVerticalGroup(
            jPanel_areaDiretorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_areaDiretorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_areaDiretorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFild_recDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_areaDiretorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_GPS)
                    .addComponent(jRadioButton_BIL))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade de Linhas Convertidas"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_linhasConvertidas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField_linhasConvertidas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_converterVarios.setText("Converter Varios Arquivos");
        jButton_converterVarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_converterVariosMouseClicked(evt);
            }
        });

        jButton_converterArquivo.setText("Converter Arquivo");
        jButton_converterArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_converterArquivoMouseClicked(evt);
            }
        });

        jButton_Zip.setText("Zip Arquivo Bil");
        jButton_Zip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ZipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_converterArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Zip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton_converterVarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_converterArquivo)
                .addGap(28, 28, 28)
                .addComponent(jButton_Zip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jButton_converterVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_areaEventosLayout = new javax.swing.GroupLayout(jPanel_areaEventos);
        jPanel_areaEventos.setLayout(jPanel_areaEventosLayout);
        jPanel_areaEventosLayout.setHorizontalGroup(
            jPanel_areaEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_areaEventosLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel_areaEventosLayout.setVerticalGroup(
            jPanel_areaEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_areaEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_areaEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel_areaDiretorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_areaEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_areaDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_areaEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_converterArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_converterArquivoMouseClicked
        diretorio = txtFild_recDiretorio.getText();
        try {
            converter.converter(this, diretorio);
            // TODO Auto-generated catch block
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_converterArquivoMouseClicked

    private void jButton_converterVariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_converterVariosMouseClicked
        for (int i = 0; i < diretorios.size(); i++) {
            try {
                converter.converter(this, diretorios.get(i));
            } catch (Exception ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_converterVariosMouseClicked

    private void jButton_abrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrirArquivoActionPerformed
        jButton_converterArquivo.setEnabled(true);
        jButton_converterVarios.setEnabled(true);
        jButton_Zip.setEnabled(true);
        abrirArquivo();
    }//GEN-LAST:event_jButton_abrirArquivoActionPerformed

    private void jButton_abrirPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abrirPastaActionPerformed
        jButton_converterArquivo.setEnabled(true);
        jButton_converterVarios.setEnabled(true);
        jButton_Zip.setEnabled(true);
        abrirVariosArquivos();
    }//GEN-LAST:event_jButton_abrirPastaActionPerformed

    private void jButton_ZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ZipActionPerformed
        abrirVariosArquivos();
        zipArquivo();
    }//GEN-LAST:event_jButton_ZipActionPerformed

    private void jRadioButton_GPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_GPSMouseClicked
        jRadioButton_BIL.setSelected(false);
        jRadioButton_GPS.setSelected(true);
    }//GEN-LAST:event_jRadioButton_GPSMouseClicked

    private void jRadioButton_BILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton_BILMouseClicked
        jRadioButton_GPS.setSelected(false);
        jRadioButton_BIL.setSelected(true);
    }//GEN-LAST:event_jRadioButton_BILMouseClicked

    private void jRadioButton_BILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_BILActionPerformed
        if(jRadioButton_BIL.isSelected()) {
            jButton_converterVarios.setEnabled(false);
            jButton_converterArquivo.setEnabled(false);
            jButton_Zip.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton_BILActionPerformed

    private void jRadioButton_GPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_GPSActionPerformed
        if(jRadioButton_GPS.isSelected()) {
            jButton_converterVarios.setEnabled(true);
            jButton_converterArquivo.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButton_GPSActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Zip;
    private javax.swing.JButton jButton_abrirArquivo;
    private javax.swing.JButton jButton_abrirPasta;
    private javax.swing.JButton jButton_converterArquivo;
    private javax.swing.JButton jButton_converterVarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_areaDiretorio;
    private javax.swing.JPanel jPanel_areaEventos;
    private javax.swing.JRadioButton jRadioButton_BIL;
    private javax.swing.JRadioButton jRadioButton_GPS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_linhasConvertidas;
    private javax.swing.JTextField txtFild_recDiretorio;
    // End of variables declaration//GEN-END:variables

    public void setjTextField_linhasConvertidas(String x) {
        jTextField_linhasConvertidas.setText(x);
    }

    private void abrirVariosArquivos() {
        diretorios = new ArrayList<>();
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retorno = chooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            File dados = chooser.getSelectedFile();
            File arquivos[] = dados.listFiles();
            for (int i = 0; i < arquivos.length; i++) {
                diretorios.add(arquivos[i].getAbsolutePath());
            }
            txtFild_recDiretorio.setText(dados.getAbsolutePath());

        }
    }

    private void abrirArquivo() {
        diretorios = new ArrayList<>();
        JFileChooser chooser = new JFileChooser();
        int retorno = chooser.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            txtFild_recDiretorio.setText(chooser.getSelectedFile().getAbsolutePath());
            diretorios.add(chooser.getSelectedFile().getAbsolutePath());
        }
    }

    private void zipArquivo() {

        new Thread() {
            public void run() {

                for (int i = 0; i < diretorios.size(); i++) {
                    try {
                        sleep(100);
                        jTextField_linhasConvertidas.setText("Zipando Arquivo(s) " + i);
                       
                        if (jRadioButton_BIL.isSelected()) {
                            zip.compactarParaZip(diretorios.get(i).replace(".bil", "") + ".zip", diretorios.get(i));
                        } else {
                            zip.compactarParaZip(diretorios.get(i).replace(".gps", "")+".zip",diretorios.get(i));
                        }
                        
                    } catch (Exception ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                jTextField_linhasConvertidas.setText("Arquivo(s) Zipado");

            }
        }.start();
    }

}

